default:
  plugins:
    - image
    - link

alternate:
  menubar: false
  selector: .textarea
  toolbar: uploadimage
  width: 100%
  auto_focus: true
  indentation : '0px'
  object_resizing : false
  paste_retain_style_properties: "all"
  entity_encoding: raw
  relative_urls: false
  plugins:
    - table


